#
# Copyright 2025-2026 Infradise Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: typeredis
description: A high-performance, cluster-aware, type-safe Dart client for Redis, Valkey, and compatible servers.
version: 3.8.1
repository: https://github.com/infradise/TypeRedis
homepage: https://github.com/infradise/TypeRedis
issue_tracker: https://github.com/infradise/TypeRedis/issues
# documentation: https://github.com/infradise/TypeRedis/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  async: ^2.13.0
  dart_flutter_team_lints: ^3.5.2
  lints: ^6.1.0
  stream_channel: ^2.1.4
  test: ^1.25.0